title: Cyberdelia NYC
author: Cyberdelia NYC # name of site's author
url: https://www.cyberdelianyc.com # root address of the site
# baseurl: "/no-style-please" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
tagline: Ultimate cyberpunk lounge/club destination.
description: The Crime is Curiosity. Ultimate cyberpunk lounge/club destination for random moments of Hackers movie nostalgia and lols. 📍NYC/London/Fictional

social:
  name: cyberdelianyc
  links:
    - https://twitter.com/cyberdelianyc

twitter:
  username: cyberdelianyc

permalink: /posts/:categories/:title

defaults:
  - scope:
      path: ""
    values:
      image: /images/hackers_0594-cyberdelia-dade-kate-2-1024x-comp.jpg

favicon: "hackers_0546-cyberdeliaflyer-white-544x544-circle.png" # name+extension of favicon (which must be put on the root folder)
logo: "hackers_0546-cyberdeliaflyer-white-544x544-circle.png"
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
